version: '3.3'
services:

  database:
    image: mysql:8.0.27
    container_name: database
    environment:
      MYSQL_DATABASE: 'kry'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - database-volume:/var/lib/mysql

volumes:
  database-volume: