spring:
  data:
    elasticsearch:
      client:
        reactive:
          endpoints: "localhost:9200"
  elasticsearch:
    rest:
      uris:
        - "http://localhost:9200"

logging:
  level:
    root: info

server:
  port: 8080
  servlet:
    context-path: /

http-methods-to-block:
  log-level: WARN
  methods: OPTIONS, TRACE

management:
  server:
    port: 8081
  endpoints:
    enabled-by-default: true
    web:
      base-path: /
      exposure:
        include: 'health, metrics, prometheus, ping, healthcheck'


