spring:
  r2dbc:
    url: "r2dbc:pool:mysql://localhost:3306/kry"
    password: "password"
    username: "user"

  flyway:
    schemas: kry
    url: "jdbc:mysql://localhost:3306/kry"
    user: ${spring.r2dbc.username}
    password: ${spring.r2dbc.password}
    baseline-on-migrate: true

logging:
  level:
    root: info

server:
  port: 8080

http-methods-to-block:
  log-level: WARN
  methods: OPTIONS, TRACE

management:
  server:
    port: 8081
  endpoints:
    enabled-by-default: true
    web:
      base-path: /
      exposure:
        include: 'health, metrics, prometheus, ping, healthcheck'


